---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod1
  labels:
    app: httpd1
spec:
  containers:
  - name: httpd-conatiner
    image: httpd:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd1
  ports:
  - protocol: TCP
    port: 7895
    targetPort: 80
    nodePort: 31001

