---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins-container
    image: jenkins/jenkins
    ports:
    - containerPort: 8080
    - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: port4
    protocol: TCP
    port: 6541
    targetPort: 8080
    nodePort: 31105
  - name: port5
    protocol: TCP
    port: 6542
    targetPort: 50000
    nodePort: 31106
