apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql1
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "mysql"
    ports:
      - containerPort: 3306
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-volume
  volumes:
    - name: mysql-volume
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: mysql1
  ports:
    - port: 6987
      targetPort: 3306
      nodePort: 32406

