---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx1
spec:
  containers:
  - name: nginx-conatiner
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx1
  ports:
  - protocol: TCP
    port: 7894
    targetPort: 80
    nodePort: 31000
