---
apiVersion: v1
kind: Pod
metadata:
  name: proxy-pod
  labels:
    app: ng-proxy
spec:
  containers:
  - name: proxy-container
    image: jc21/nginx-proxy-manager
    ports:
    - containerPort: 80
    - containerPort: 81
    volumeMounts:
    - name: proxy-volume
      mountPath: /etc/letsencrypt
  volumes:
  - name: proxy-volume
    emptyDir:
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  type: NodePort
  selector:
    app: ng-proxy
  ports:
  - name: http
    protocol: TCP
    port: 9874
    targetPort: 80
    nodePort: 30003
  - name: admin
    protocol: TCP
    port: 9876
    targetPort: 81
    nodePort: 30005
