apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres1
spec:
  containers:
  - name: postgres
    image: postgres:latest
    env:
      - name: POSTGRES_PASSWORD
        value: "asd"
    ports:
      - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres1
  ports:
    - port: 6989
      targetPort: 5432
      nodePort: 32200

