apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ubuntu-dep
  template:
    metadata:
      labels:
        app: ubuntu-dep
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu:latest
        command: ["sleep","infinity"]
